/// <reference types="vitest/globals" />
// Phase 6: Markdown Export tests — all sections, Pinia-backed, node environment
// Pattern: createPinia() + setActivePinia() in each beforeEach for test isolation
// Phase 13: Updated mocks to use workloadDomains[0] multi-domain store shape
// Phase 14: Updated per-domain sections from H2 to H3 (multi-domain loop)

import { createPinia, setActivePinia } from 'pinia'
import { useInputStore } from '@/stores/inputStore'
import { generateMarkdownReport } from './useMarkdownExport'

describe('generateMarkdownReport — always-present sections', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
  })

  it('contains report title # VCF 9.x Sizing Report', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('# VCF 9.x Sizing Report')
  })

  it('contains ### Host Configuration section (H3, inside domain block)', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('### Host Configuration')
  })

  it('contains ## Management Domain Overhead section', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('## Management Domain Overhead')
  })

  it('contains ### Compute Sizing section (H3, inside domain block)', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('### Compute Sizing')
  })

  it('contains ### Storage Sizing section (H3, inside domain block)', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('### Storage Sizing')
  })

  it('contains ### Workload Profile section (H3, inside domain block)', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('### Workload Profile')
  })

  it('contains ### Network Configuration section (H3, inside domain block)', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('### Network Configuration')
  })

  it('contains footer attribution *Generated by VCF Sizer', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('*Generated by VCF Sizer')
  })

  it('report contains no undefined or NaN values', () => {
    const report = generateMarkdownReport()
    expect(report).not.toContain('undefined')
    expect(report).not.toContain('NaN')
  })
})

describe('generateMarkdownReport — MD-02 Workload Profile', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
  })

  it('shows VM count row matching store default (100)', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('100')
  })

  it('shows vCPU per VM row matching store default (4)', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('| vCPU per VM')
  })
})

describe('generateMarkdownReport — MD-03 Management Architecture', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
  })

  it('shows management architecture row (default: shared)', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('shared')
  })

  it('dedicated host count row absent when managementArchitecture=shared (default)', () => {
    const report = generateMarkdownReport()
    expect(report).not.toContain('Dedicated host count')
  })

  it('dedicated host count row present when managementArchitecture=dedicated', () => {
    const input = useInputStore()
    input.managementArchitecture = 'dedicated'
    const report = generateMarkdownReport()
    expect(report).toContain('Dedicated host count')
  })
})

describe('generateMarkdownReport — MD-04 NVMe Tiering', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
  })

  it('NVMe section absent when nvmeTieringEnabled=false (default)', () => {
    const report = generateMarkdownReport()
    expect(report).not.toContain('### NVMe')
  })

  it('NVMe section present when nvmeTieringEnabled=true', () => {
    const input = useInputStore()
    input.workloadDomains[0].nvmeTieringEnabled = true
    input.workloadDomains[0].activeMemoryPct = 60
    const report = generateMarkdownReport()
    expect(report).toContain('### NVMe')
  })
})

describe('generateMarkdownReport — MD-05 AI/GPU', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
  })

  it('AI/GPU section absent when gpuVmCount=0 (default)', () => {
    const report = generateMarkdownReport()
    expect(report).not.toContain('### AI/GPU')
  })

  it('AI/GPU section present when gpuVmCount=5', () => {
    const input = useInputStore()
    input.workloadDomains[0].gpuVmCount = 5
    input.workloadDomains[0].vgpuMemoryGB = 32
    const report = generateMarkdownReport()
    expect(report).toContain('### AI/GPU')
  })

  it('AI/GPU section shows GPU VM count row with value 5', () => {
    const input = useInputStore()
    input.workloadDomains[0].gpuVmCount = 5
    input.workloadDomains[0].vgpuMemoryGB = 32
    const report = generateMarkdownReport()
    expect(report).toContain('5')
  })
})

describe('generateMarkdownReport — MD-06 Stretch Cluster', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
  })

  it('Stretch section absent when deploymentMode=ha (default)', () => {
    const report = generateMarkdownReport()
    expect(report).not.toContain('### Stretch Cluster')
  })

  it('Stretch section present when deploymentMode=stretch', () => {
    const input = useInputStore()
    input.workloadDomains[0].deploymentMode = 'stretch'
    const report = generateMarkdownReport()
    expect(report).toContain('### Stretch Cluster')
  })

  it('Stretch section contains Min inter-site bandwidth row', () => {
    const input = useInputStore()
    input.workloadDomains[0].deploymentMode = 'stretch'
    const report = generateMarkdownReport()
    expect(report).toContain('Min inter-site bandwidth')
  })

  it('Stretch section contains Witness vCPU and Witness RAM rows', () => {
    const input = useInputStore()
    input.workloadDomains[0].deploymentMode = 'stretch'
    const report = generateMarkdownReport()
    expect(report).toContain('Witness vCPU')
    expect(report).toContain('Witness RAM')
  })
})

describe('generateMarkdownReport — MD-07 vSAN Max', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
  })

  it('vSAN Max section absent when storageType=vsan-esa (default)', () => {
    const report = generateMarkdownReport()
    expect(report).not.toContain('### vSAN Max')
  })

  it('vSAN Max section present when storageType=vsan-max', () => {
    const input = useInputStore()
    input.workloadDomains[0].storageType = 'vsan-max'
    const report = generateMarkdownReport()
    expect(report).toContain('### vSAN Max')
  })

  it('vSAN Max section shows ReadyNode profile row', () => {
    const input = useInputStore()
    input.workloadDomains[0].storageType = 'vsan-max'
    const report = generateMarkdownReport()
    expect(report).toContain('ReadyNode profile')
  })
})

describe('generateMarkdownReport — MD-08 Validation Warnings', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
  })

  it('Validation warnings section absent with default valid inputs', () => {
    const report = generateMarkdownReport()
    expect(report).not.toContain('## Validation Warnings')
  })

  it('Validation warnings section present when hostCount triggers warning', () => {
    const input = useInputStore()
    input.workloadDomains[0].hostCount = 1
    input.workloadDomains[0].deploymentMode = 'ha'
    const report = generateMarkdownReport()
    expect(report).toContain('## Validation Warnings')
  })
})

describe('generateMarkdownReport — MD-09 Network Configuration', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
  })

  it('Network config section present (always, H3 inside domain block)', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('### Network Configuration')
  })

  it('Network config shows network speed row', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('Network speed')
  })

  it('Network config shows dedup status row', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('Dedup')
  })
})

describe('generateMarkdownReport — table structure', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
  })

  it('report contains at least 10 markdown table rows (| ... |)', () => {
    const report = generateMarkdownReport()
    const tableRows = report.split('\n').filter((line) => line.startsWith('|'))
    expect(tableRows.length).toBeGreaterThanOrEqual(10)
  })
})

describe('generateMarkdownReport — no regression', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
  })

  it('Recommended Host Count row is present in compute section', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('Recommended Host Count')
  })

  it('Safe usable capacity row is present in storage section', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('Safe usable capacity')
  })

  it('CPU utilization formatted to 1 decimal place (matches /\\d+\\.\\d%/)', () => {
    const report = generateMarkdownReport()
    expect(report).toMatch(/\d+\.\d%/)
  })
})

describe('generateMarkdownReport — multi-domain (EXP-01, EXP-02)', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
  })

  it('includes one named section per workload domain', () => {
    const input = useInputStore()
    // Add a second domain and rename it
    input.addDomain()
    input.updateDomain(input.workloadDomains[1].id, { name: 'WLD-2' })
    const report = generateMarkdownReport()
    expect(report).toContain('## Domain: WLD-1')
    expect(report).toContain('## Domain: WLD-2')
  })

  it('uses H3 sub-sections within each domain block', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('### Host Configuration')
    expect(report).toContain('### Compute Sizing')
  })

  it('includes aggregate totals section', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('## Aggregate Totals')
  })

  it('aggregate totals includes total recommended hosts', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('Total recommended hosts')
  })

  it('management architecture appears exactly once', () => {
    const input = useInputStore()
    input.addDomain()
    input.updateDomain(input.workloadDomains[1].id, { name: 'WLD-2' })
    const report = generateMarkdownReport()
    const occurrences = report.split('## Management Architecture').length - 1
    expect(occurrences).toBe(1)
  })

  it('management domain overhead appears exactly once', () => {
    const input = useInputStore()
    input.addDomain()
    input.updateDomain(input.workloadDomains[1].id, { name: 'WLD-2' })
    const report = generateMarkdownReport()
    const occurrences = report.split('## Management Domain Overhead').length - 1
    expect(occurrences).toBe(1)
  })

  it('conditional GPU section only in domain that enables it', () => {
    const input = useInputStore()
    // Domain 1 (WLD-1): no GPU
    input.updateDomain(input.workloadDomains[0].id, { gpuVmCount: 0, name: 'WLD-1' })
    // Add domain 2 (WLD-2): with GPU
    input.addDomain()
    input.updateDomain(input.workloadDomains[1].id, { name: 'WLD-2', gpuVmCount: 2, vgpuMemoryGB: 16 })
    const report = generateMarkdownReport()
    // GPU section should appear after WLD-2 heading
    const wld2Pos = report.indexOf('## Domain: WLD-2')
    const gpuPos = report.indexOf('### AI/GPU Workloads')
    expect(gpuPos).toBeGreaterThan(wld2Pos)
    // GPU section should NOT appear between report start and WLD-2 heading
    const wld1Pos = report.indexOf('## Domain: WLD-1')
    expect(gpuPos).toBeGreaterThan(wld1Pos)
    // No GPU section in the part before WLD-2
    const reportBeforeWld2 = report.substring(0, wld2Pos)
    expect(reportBeforeWld2).not.toContain('### AI/GPU Workloads')
  })
})
