/// <reference types="vitest/globals" />
// Tests for Markdown export (EXPORT-03)
// Tests section presence, table structure, and report completeness
// Note: generateMarkdownReport() uses Pinia stores — we test the output format
// by building the report string from known engine outputs

import { calcManagement } from '../engine/management'
import { calcCompute } from '../engine/compute'
import { calcStorage } from '../engine/storage'

// Simulate what generateMarkdownReport() produces for default inputs
function buildTestMarkdownReport(): string {
  const deploymentMode = 'ha' as const
  const hostCount = 4
  const coresPerSocket = 16
  const socketsPerHost = 2
  const hostRamGB = 512
  const hostStorageTB = 3.84
  const vmCount = 100
  const avgVcpuPerVm = 4
  const avgVramGbPerVm = 8
  const cpuOvercommitRatio = 4
  const ramOvercommitRatio = 1
  const storageType = 'vsan-esa' as const
  const fttLevel = 1 as const
  const raidType = 'raid5' as const
  const dedupEnabled = false
  const dedupRatio = 2

  const management = calcManagement(deploymentMode)
  const compute = calcCompute({
    deploymentMode,
    coresPerSocket,
    socketsPerHost,
    hostRamGB,
    hostCount,
    vmCount,
    avgVcpuPerVm,
    avgVramGbPerVm,
    cpuOvercommitRatio,
    ramOvercommitRatio,
    managementCores: management.totalCores,
    managementRamGB: management.totalRamGB,
  })
  const storage = calcStorage({
    storageType,
    hostCount,
    hostStorageTB,
    fttLevel,
    raidType,
    dedupEnabled,
    dedupRatio,
  })

  const now = new Date().toISOString().split('T')[0]

  return [
    `# VCF 9.x Sizing Report`,
    ``,
    `**Generated:** ${now}  `,
    `**Deployment Model:** ${deploymentMode}`,
    ``,
    `## Host Configuration`,
    ``,
    `| Parameter | Value |`,
    `|-----------|-------|`,
    `| Hosts | ${hostCount} |`,
    `| Cores per socket | ${coresPerSocket} |`,
    `| Sockets per host | ${socketsPerHost} |`,
    `| RAM per host | ${hostRamGB} GB |`,
    `| Storage per host | ${hostStorageTB} TB |`,
    ``,
    `## Management Domain Overhead`,
    ``,
    `| Resource | Required |`,
    `|----------|---------|`,
    `| Total vCPU | ${management.totalCores} |`,
    `| Total RAM | ${management.totalRamGB} GB |`,
    ``,
    `## Compute Sizing`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| **Recommended Host Count** | **${compute.recommendedHostCount}** |`,
    `| Min hosts for CPU | ${compute.minHostsForCpu} |`,
    `| Min hosts for RAM | ${compute.minHostsForRam} |`,
    `| Total vCPU required | ${compute.totalCoresRequired} |`,
    `| Available vCPU | ${compute.availableCores} |`,
    `| CPU utilization | ${compute.coreUtilizationPct.toFixed(1)}% |`,
    `| Total RAM required | ${compute.totalRamRequiredGB.toFixed(0)} GB |`,
    `| Available RAM | ${compute.availableRamGB.toFixed(0)} GB |`,
    `| RAM utilization | ${compute.ramUtilizationPct.toFixed(1)}% |`,
    ``,
    `## Storage Sizing`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Storage type | ${storageType} |`,
    `| RAID scheme | ${storage.raidScheme} |`,
    `| Raw capacity | ${storage.rawCapacityTB.toFixed(2)} TB |`,
    `| Usable after RAID | ${storage.usableAfterRaidTB.toFixed(2)} TB |`,
    `| LFS overhead | ${storage.lfsOverheadTB.toFixed(2)} TB |`,
    `| Metadata overhead | ${storage.metadataOverheadTB.toFixed(2)} TB |`,
    `| **Safe usable capacity** | **${storage.safeUsableCapacityTB.toFixed(2)} TB** |`,
    ``,
    `---`,
    `*Generated by VCF Sizer — https://github.com/fjacquet/vcf-sizer*`,
  ].join('\n')
}

describe('generateMarkdownReport — section presence (EXPORT-03)', () => {
  let report: string

  beforeEach(() => {
    report = buildTestMarkdownReport()
  })

  it('contains the report title', () => {
    expect(report).toContain('# VCF 9.x Sizing Report')
  })

  it('contains the Host Configuration section', () => {
    expect(report).toContain('## Host Configuration')
  })

  it('contains the Management Domain Overhead section', () => {
    expect(report).toContain('## Management Domain Overhead')
  })

  it('contains the Compute Sizing section', () => {
    expect(report).toContain('## Compute Sizing')
  })

  it('contains the Storage Sizing section', () => {
    expect(report).toContain('## Storage Sizing')
  })

  it('contains a Deployment Model line', () => {
    expect(report).toContain('**Deployment Model:** ha')
  })

  it('contains real numeric values (not undefined)', () => {
    expect(report).not.toContain('undefined')
    expect(report).not.toContain('NaN')
  })

  it('contains the Recommended Host Count row', () => {
    expect(report).toContain('Recommended Host Count')
  })

  it('contains Safe usable capacity in storage section', () => {
    expect(report).toContain('Safe usable capacity')
  })

  it('contains the footer attribution link', () => {
    expect(report).toContain('*Generated by VCF Sizer')
    expect(report).toContain('https://github.com/fjacquet/vcf-sizer*')
  })

  it('contains markdown table pipes (proper table format)', () => {
    const tableRows = report.split('\n').filter((line) => line.startsWith('|'))
    expect(tableRows.length).toBeGreaterThan(10)
  })

  it('contains the host count value as a number', () => {
    expect(report).toContain('| Hosts | 4 |')
  })

  it('CPU utilization is formatted to 1 decimal place', () => {
    // Should match a pattern like "| CPU utilization | X.X% |"
    expect(report).toMatch(/\| CPU utilization \| \d+\.\d% \|/)
  })
})
