/// <reference types="vitest/globals" />
// Phase 6: Markdown Export tests — all sections, Pinia-backed, node environment
// Pattern: createPinia() + setActivePinia() in each beforeEach for test isolation
// Wave 0 purpose: establish RED tests before implementation (TDD gate)

import { createPinia, setActivePinia } from 'pinia'
import { useInputStore } from '@/stores/inputStore'
import { generateMarkdownReport } from './useMarkdownExport'

describe('generateMarkdownReport — always-present sections', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
  })

  it('contains report title # VCF 9.x Sizing Report', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('# VCF 9.x Sizing Report')
  })

  it('contains ## Host Configuration section', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('## Host Configuration')
  })

  it('contains ## Management Domain Overhead section', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('## Management Domain Overhead')
  })

  it('contains ## Compute Sizing section', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('## Compute Sizing')
  })

  it('contains ## Storage Sizing section', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('## Storage Sizing')
  })

  it('contains ## Workload Profile section', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('## Workload Profile')
  })

  it('contains ## Network Configuration section', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('## Network Configuration')
  })

  it('contains footer attribution *Generated by VCF Sizer', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('*Generated by VCF Sizer')
  })

  it('report contains no undefined or NaN values', () => {
    const report = generateMarkdownReport()
    expect(report).not.toContain('undefined')
    expect(report).not.toContain('NaN')
  })
})

describe('generateMarkdownReport — MD-02 Workload Profile', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
  })

  it('shows VM count row matching store default (100)', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('100')
  })

  it('shows vCPU per VM row matching store default (4)', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('| vCPU per VM')
  })
})

describe('generateMarkdownReport — MD-03 Management Architecture', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
  })

  it('shows management architecture row (default: shared)', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('shared')
  })

  it('dedicated host count row absent when managementArchitecture=shared (default)', () => {
    const report = generateMarkdownReport()
    expect(report).not.toContain('Dedicated host count')
  })

  it('dedicated host count row present when managementArchitecture=dedicated', () => {
    const input = useInputStore()
    input.managementArchitecture = 'dedicated'
    const report = generateMarkdownReport()
    expect(report).toContain('Dedicated host count')
  })
})

describe('generateMarkdownReport — MD-04 NVMe Tiering', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
  })

  it('NVMe section absent when nvmeTieringEnabled=false (default)', () => {
    const report = generateMarkdownReport()
    expect(report).not.toContain('## NVMe')
  })

  it('NVMe section present when nvmeTieringEnabled=true', () => {
    const input = useInputStore()
    input.nvmeTieringEnabled = true
    input.activeMemoryPct = 60
    const report = generateMarkdownReport()
    expect(report).toContain('## NVMe')
  })
})

describe('generateMarkdownReport — MD-05 AI/GPU', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
  })

  it('AI/GPU section absent when gpuVmCount=0 (default)', () => {
    const report = generateMarkdownReport()
    expect(report).not.toContain('## AI/GPU')
  })

  it('AI/GPU section present when gpuVmCount=5', () => {
    const input = useInputStore()
    input.gpuVmCount = 5
    input.vgpuMemoryGB = 32
    const report = generateMarkdownReport()
    expect(report).toContain('## AI/GPU')
  })

  it('AI/GPU section shows GPU VM count row with value 5', () => {
    const input = useInputStore()
    input.gpuVmCount = 5
    input.vgpuMemoryGB = 32
    const report = generateMarkdownReport()
    expect(report).toContain('5')
  })
})

describe('generateMarkdownReport — MD-06 Stretch Cluster', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
  })

  it('Stretch section absent when deploymentMode=ha (default)', () => {
    const report = generateMarkdownReport()
    expect(report).not.toContain('## Stretch Cluster')
  })

  it('Stretch section present when deploymentMode=stretch', () => {
    const input = useInputStore()
    input.deploymentMode = 'stretch'
    const report = generateMarkdownReport()
    expect(report).toContain('## Stretch Cluster')
  })

  it('Stretch section contains Min inter-site bandwidth row', () => {
    const input = useInputStore()
    input.deploymentMode = 'stretch'
    const report = generateMarkdownReport()
    expect(report).toContain('Min inter-site bandwidth')
  })

  it('Stretch section contains Witness vCPU and Witness RAM rows', () => {
    const input = useInputStore()
    input.deploymentMode = 'stretch'
    const report = generateMarkdownReport()
    expect(report).toContain('Witness vCPU')
    expect(report).toContain('Witness RAM')
  })
})

describe('generateMarkdownReport — MD-07 vSAN Max', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
  })

  it('vSAN Max section absent when storageType=vsan-esa (default)', () => {
    const report = generateMarkdownReport()
    expect(report).not.toContain('## vSAN Max')
  })

  it('vSAN Max section present when storageType=vsan-max', () => {
    const input = useInputStore()
    input.storageType = 'vsan-max'
    const report = generateMarkdownReport()
    expect(report).toContain('## vSAN Max')
  })

  it('vSAN Max section shows ReadyNode profile row', () => {
    const input = useInputStore()
    input.storageType = 'vsan-max'
    const report = generateMarkdownReport()
    expect(report).toContain('ReadyNode profile')
  })
})

describe('generateMarkdownReport — MD-08 Validation Warnings', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
  })

  it('Validation warnings section absent with default valid inputs', () => {
    const report = generateMarkdownReport()
    expect(report).not.toContain('## Validation Warnings')
  })

  it('Validation warnings section present when hostCount triggers warning', () => {
    const input = useInputStore()
    input.hostCount = 1
    input.deploymentMode = 'ha'
    const report = generateMarkdownReport()
    expect(report).toContain('## Validation Warnings')
  })
})

describe('generateMarkdownReport — MD-09 Network Configuration', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
  })

  it('Network config section present (always)', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('## Network Configuration')
  })

  it('Network config shows network speed row', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('Network speed')
  })

  it('Network config shows dedup status row', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('Dedup')
  })
})

describe('generateMarkdownReport — table structure', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
  })

  it('report contains at least 10 markdown table rows (| ... |)', () => {
    const report = generateMarkdownReport()
    const tableRows = report.split('\n').filter((line) => line.startsWith('|'))
    expect(tableRows.length).toBeGreaterThanOrEqual(10)
  })
})

describe('generateMarkdownReport — no regression', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
  })

  it('Recommended Host Count row is present in compute section', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('Recommended Host Count')
  })

  it('Safe usable capacity row is present in storage section', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('Safe usable capacity')
  })

  it('CPU utilization formatted to 1 decimal place (matches /\\d+\\.\\d%/)', () => {
    const report = generateMarkdownReport()
    expect(report).toMatch(/\d+\.\d%/)
  })
})

describe('generateMarkdownReport -- EXPORT-01 management hosts in aggregate', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
  })

  it('aggregate section contains Management hosts row (default colocated)', () => {
    const report = generateMarkdownReport()
    expect(report).toContain('| Management hosts |')
    expect(report).toContain('colocated with WLD-1')
  })

  it('aggregate section shows numeric host count when dedicated', () => {
    const input = useInputStore()
    input.managementArchitecture = 'dedicated'
    const report = generateMarkdownReport()
    expect(report).toContain('| Management hosts |')
    // Should NOT contain "colocated" in the management hosts row
    const lines = report.split('\n').filter(l => l.includes('Management hosts'))
    expect(lines.length).toBeGreaterThanOrEqual(1)
    const mgmtLine = lines.find(l => l.includes('Aggregate') === false) ?? lines[0]
    expect(mgmtLine).not.toContain('colocated')
  })
})
