// Markdown export composable — generates complete VCF sizing report as Markdown string
// Extracted from useUrlState.ts (MD-01). Wave 2 will enrich with sections MD-02 through MD-09.
// This is a plain TypeScript module — NO Vue lifecycle hooks (CALC-01/CALC-02 compliant)
import { useInputStore } from '@/stores/inputStore'
import { useCalculationStore } from '@/stores/calculationStore'

/**
 * generateMarkdownReport — called on Markdown export click.
 * Pure string template, no library. Snapshot of current computed values.
 * Returns a string only — all download/Blob logic stays in ExportToolbar.vue (Pitfall 5).
 */
export function generateMarkdownReport(): string {
  const calc = useCalculationStore()
  const store = useInputStore()
  const now = new Date().toISOString().split('T')[0]

  return [
    `# VCF 9.x Sizing Report`,
    ``,
    `**Generated:** ${now}  `,
    `**Deployment Model:** ${store.deploymentMode}`,
    ``,
    `## Host Configuration`,
    ``,
    `| Parameter | Value |`,
    `|-----------|-------|`,
    `| Hosts | ${store.hostCount} |`,
    `| Cores per socket | ${store.coresPerSocket} |`,
    `| Sockets per host | ${store.socketsPerHost} |`,
    `| RAM per host | ${store.hostRamGB} GB |`,
    `| Storage per host | ${store.hostStorageTB} TB |`,
    ``,
    `## Management Domain Overhead`,
    ``,
    `| Resource | Required |`,
    `|----------|---------|`,
    `| Total vCPU | ${calc.management.totalCores} |`,
    `| Total RAM | ${calc.management.totalRamGB} GB |`,
    ``,
    `## Compute Sizing`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| **Recommended Host Count** | **${calc.compute.recommendedHostCount}** |`,
    `| Min hosts for CPU | ${calc.compute.minHostsForCpu} |`,
    `| Min hosts for RAM | ${calc.compute.minHostsForRam} |`,
    `| Total vCPU required | ${calc.compute.totalCoresRequired} |`,
    `| Available vCPU | ${calc.compute.availableCores} |`,
    `| CPU utilization | ${calc.compute.coreUtilizationPct.toFixed(1)}% |`,
    `| Total RAM required | ${calc.compute.totalRamRequiredGB.toFixed(0)} GB |`,
    `| Available RAM | ${calc.compute.availableRamGB.toFixed(0)} GB |`,
    `| RAM utilization | ${calc.compute.ramUtilizationPct.toFixed(1)}% |`,
    ``,
    `## Storage Sizing`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Storage type | ${store.storageType} |`,
    `| RAID scheme | ${calc.storage.raidScheme} |`,
    `| Raw capacity | ${calc.storage.rawCapacityTB.toFixed(2)} TB |`,
    `| Usable after RAID | ${calc.storage.usableAfterRaidTB.toFixed(2)} TB |`,
    `| LFS overhead | ${calc.storage.lfsOverheadTB.toFixed(2)} TB |`,
    `| Metadata overhead | ${calc.storage.metadataOverheadTB.toFixed(2)} TB |`,
    `| **Safe usable capacity** | **${calc.storage.safeUsableCapacityTB.toFixed(2)} TB** |`,
    ``,
    `---`,
    `*Generated by VCF Sizer — https://github.com/fjacquet/vcf-sizer*`,
  ].join('\n')
}
